# 异常测试

*项目：junit-exception*

​	Java程序中的异常处理很重要。对于自己编写的方法，我们也应当清楚在哪里抛出什么样的异常，抛出的异常应该也要纳入测试的范围内。



## @assertThrows()

```java
public static <T extends Throwable> T assertThrows(Class<T> expectedThrowable, ThrowingRunnable runnable) {
        return assertThrows((String)null, expectedThrowable, runnable);
}
```

​	assertThrows()方法接收的参数是指定的异常类，和一个函数式接口。在函数式接口中写下会抛出异常的程序情况来捕获异常

```java
	@Test
	public void testNegative() {
		assertThrows(IllegalArgumentException.class, new ThrowingRunnable() {
			@Override
			public void run() throws Throwable {
				Factorial.fact(-1);
			}
		});
		assertThrows(IllegalArgumentException.class, () -> {
			Factorial.fact(-1);
		});
	}
```

